<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net7.0-android;</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.OneSignal</PackageId>
		<PackageVersion>5.1.5</PackageVersion>
		<AssemblyVersion>5.1.5</AssemblyVersion>
		<FileVersion>5.1.5</FileVersion>
		<Version>5.1.5</Version>
		<Title>Anjo Android OneSignal SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.OneSignal</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) Binding Library - OneSignal SDK</Description>
		<PackageReleaseNotes>OneSignal SDK v5.1.5</PackageReleaseNotes>
		<Copyright>Copyright (c) 2024 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, OneSignal, push notification</PackageTags>
		<Summary>OneSignal is a free email, sms, push notification, and in-app message service for mobile apps. This plugin makes it easy to integrate your native Android or Amazon app with OneSignal.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Jars\OneSignal-5.1.5.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Anjo.Android.OneSignal.Core\Anjo.Android.OneSignal.Core.csproj" />
	  <ProjectReference Include="..\Anjo.Android.OneSignal.InAppMessages\Anjo.Android.OneSignal.InAppMessages.csproj" />
	  <ProjectReference Include="..\Anjo.Android.OneSignal.Location\Anjo.Android.OneSignal.Location.csproj" />
	  <ProjectReference Include="..\Anjo.Android.OneSignal.Notifications\Anjo.Android.OneSignal.Notifications.csproj" />
	</ItemGroup> 
</Project>